### ISSUE TITLE
Kafka service call doesn't find event

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-core#2350]
Hello,

I meet an issue with a test using kafka service type. Everything seem correctly set up, but Cerberus can't find any event.
Keystore & truststore are available in /opt/config/
Test case:
![image](https://user-images.githubusercontent.com/18569182/149944693-35f38fa2-a149-4865-91db-3e362dbd7b82.png)
Service:
![image](https://user-images.githubusercontent.com/18569182/149944969-9a91e953-32d3-4239-8ab4-8a2653d41012.png)
Execution:
![image](https://user-images.githubusercontent.com/18569182/149945052-011cb35a-3118-4af5-a7e8-1a65c572cd38.png)
Cerberus Logs:

> 2022-01-18 13:13:39 INFO  KafkaService:322 - Open Consumer : xxx.aivencloud.com:xxx|stockimpactmovements
2022-01-18 13:13:42 ERROR KafkaService:419 - org.json.JSONException: A JSONObject text must begin with '{' at character 0
org.json.JSONException: A JSONObject text must begin with '{' at character 0
	at org.json.JSONTokener.syntaxError(JSONTokener.java:496) ~[json-20080701.jar:?]
	at org.json.JSONObject.<init>(JSONObject.java:180) ~[json-20080701.jar:?]
	at org.json.JSONObject.<init>(JSONObject.java:403) ~[json-20080701.jar:?]
	at org.cerberus.service.kafka.impl.KafkaService.searchEvent(KafkaService.java:367) [classes/:?]
	at org.cerberus.service.appservice.impl.ServiceService.callService(ServiceService.java:526) [classes/:?]
	at org.cerberus.engine.gwt.impl.ActionService.doActionCallService(ActionService.java:1463) [classes/:?]
	at org.cerberus.engine.gwt.impl.ActionService.doAction(ActionService.java:367) [classes/:?]
	at org.cerberus.engine.execution.impl.ExecutionRunService.executeAction(ExecutionRunService.java:1343) [classes/:?]
	at org.cerberus.engine.execution.impl.ExecutionRunService.executeStep(ExecutionRunService.java:1226) [classes/:?]
	at org.cerberus.engine.execution.impl.ExecutionRunService.executeTestCase(ExecutionRunService.java:799) [classes/:?]
	at sun.reflect.GeneratedMethodAccessor125.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) [spring-aop-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205) [spring-aop-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at com.sun.proxy.$Proxy87.executeTestCase(Unknown Source) [?:?]
	at org.cerberus.engine.execution.impl.RunTestCaseService.runTestCase(RunTestCaseService.java:86) [classes/:?]
	at org.cerberus.servlet.zzpublic.RunTestCaseV002.doGet(RunTestCaseV002.java:343) [classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [servlet-api.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.41]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.41]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.41]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.17.0.jar:2.17.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.41]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:8.5.41]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.41]
	at org.keycloak.adapters.tomcat.AbstractAuthenticatedActionsValve.invoke(AbstractAuthenticatedActionsValve.java:67) [keycloak-tomcat-core-adapter-10.0.2.jar:10.0.2]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [catalina.jar:8.5.41]
	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181) [keycloak-tomcat-core-adapter-10.0.2.jar:10.0.2]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) [catalina.jar:8.5.41]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.41]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) [catalina.jar:8.5.41]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.41]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:8.5.41]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) [tomcat-coyote.jar:8.5.41]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:8.5.41]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) [tomcat-coyote.jar:8.5.41]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-coyote.jar:8.5.41]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.41]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.41]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

 
Cerberus4.13.1-1689 Build 20211218-210823

**Comment by vertigo17** [comment]
Hello @R-Loic , looks like the events are retrieved but the content are empty.
The connectivity looks correct.
Kafka connector expect a JSON Object that start by {. And here this looks like something different.
Can you confirm the content of the message that has been produced ?

NB : There is still something strange on the fact you put 10 sec timeout and the SEARCH returns after 13 sec. Are you sure about the config ?

**Comment by Gisele0605** [comment]
Hello @vertigo17 , here is how an event looks like on our kafka topic, I don't know if it was the information you were looking for ? 
<img width="812" alt="image" src="https://user-images.githubusercontent.com/87075657/150514692-4dd5d8d5-ce5e-4d34-8368-17045fbcdc3b.png">

As I see, there is a "{" at the beginning of the JSON.

And yes, I put 10 second timeout on the test configuration, but at the execution, there is more seconds...I tried different timeouts and everytime the test takes longer than the configuration to go on timeout (usually around 5 seconds longer)

Thanks a lot for your help

**Comment by vertigo17** [comment]
This is quite hard to debug without an access on your KAFKA instance ;-(.
Are you able to create a testcase on prod.cerberus-testing.com instance in order to reproduce from a SaaS instance ?
NB : We also use Aiven for regression testing purpose of Kafka connector and clearly don't face this issue.

**Comment by Gisele0605** [comment]
Hello,
Unfortunately I can't do it because it is sensible data that I can't share outside our company.
Is there any other way that we can debug this case ?
Thanks again
Gisèle

**Comment by vertigo17** [comment]
You can use our KAFKA Aiven tenant in order to reproduce the test you have and hopefully reproduce the issue.
If not, I don't see any other option that a dedicate onsite support to reproduce the issue on your context.

**Comment by vertigo17** [comment]
There were some improvements on KAFKA behavior linked with AVRO support. When the message cannot be converted to JSON, it reports a log with the message content.
Can you please test again and report the message catch by Cerberus ?

**Comment by vertigo17** [comment]
I close as it is not possible to reproduce. Don’t hesitate to reopen with more elements or contact me in PM in order to organise an on site support.
